import type { Metadata } from "next";
import Link from 'next/link';
import Image from 'next/image';
import "./globals.css";

import React from 'react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <header>
          <nav className="bg-gray-800 w-screen">
            <div className="flex items-center pl-8 h-14">
              <div className="flex space-x-4">
                <Link href="/" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                    Home
                </Link>
                <Link href="/blog-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                    Blog
                </Link>
                <Link href="/contact-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                    Contact
                </Link>
                <Link href="/modal-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                    Modal
                </Link>
                <Link href="/reducer-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                Reducer
                </Link>
                <Link href="/redux-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                Redux
                </Link>
              </div>
            </div>
          </nav>
        </header>
        <main className="flex flex-1 justify-center items-center flex-col w-screen">
          {children}
        </main>
        <footer className="w-full h-12 flex justify-center items-center border-t">
          <a className="flex items-center">
            Powered by 
            <Image src="/sanuna.svg" alt="Vercel Logo" width={25} height={25} className="ml-1"/>
          </a>
        </footer>
      </body>
    </html>
  );
}
